name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change this to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Build and package
        run: |
          # Add commands to build your application if necessary
          echo "Building the application..."

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <LMS>  # Replace with your Azure App Service name
          slot-name: production  # Change if you are using deployment slots
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Set up in GitHub Secrets
